# Generated by Django 4.0.4 on 2022-04-26 20:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('enquiry', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.TextField(default=True, max_length=10)),
                ('messsage', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('standard', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('PhD', 'PhD'), ('Others', 'Others')], default='1st', max_length=20)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
