# Generated by Django 4.0.4 on 2022-04-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insert',
            name='roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
