# Generated by Django 4.0.4 on 2022-04-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_insert_id_alter_insert_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insert',
            name='id',
        ),
    ]
