# Generated by Django 4.0.4 on 2022-04-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_insert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert',
            name='Id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insert',
            name='roll',
            field=models.IntegerField(default=0),
        ),
    ]
