# Generated by Django 4.0.4 on 2022-04-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_insert_id_alter_insert_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='roll',
            field=models.IntegerField(default=1),
        ),
    ]
