# Generated by Django 4.0.4 on 2022-04-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_student_delete_insert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
