# Generated by Django 4.0.4 on 2022-04-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_about_contact_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='organization',
        ),
    ]
