# Generated by Django 4.0.4 on 2022-04-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
