# Generated by Django 4.0.4 on 2022-04-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_feedback_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=30)),
                ('stdname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('contact', models.EmailField(max_length=20)),
                ('std', models.TextField(max_length=300)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=30)),
                ('stdname', models.CharField(max_length=20)),
                ('standard', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('PhD', 'PhD'), ('Others', 'Others')], default='1st', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fulname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='messsage',
        ),
        migrations.AddField(
            model_name='contact',
            name='mob',
            field=models.TextField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
