# Generated by Django 4.0.4 on 2022-04-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_insert_update_rename_name_contact_fulname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mob',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fulname',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
