# Generated by Django 4.0.4 on 2022-04-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_student_id_alter_student_roll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
