# Generated by Django 4.0.4 on 2022-04-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_student_roll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
