# Generated by Django 4.0.4 on 2022-04-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('standard', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('PhD', 'PhD'), ('Others', 'Others')], default='1st', max_length=20)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
