# Generated by Django 3.0.7 on 2022-05-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='Id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
