# Generated by Django 3.0.7 on 2022-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220501_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=1),
        ),
    ]
