# Generated by Django 3.0.7 on 2022-05-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20220502_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
